name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy Production Site (main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          cp public/CNAME dist/
          echo "semiconductorcamp.com" > dist/CNAME
          npx gh-pages -d dist -b gh-pages

      - name: Deploy Development Site (develop branch)
        if: github.ref == 'refs/heads/develop'
        run: |
          cp public/CNAME dist/
          echo "dev.semiconductorcamp.com" > dist/CNAME
          npx gh-pages -d dist -b gh-pages-dev
